Online_blog/blog/appblog/urls.py
from django.urls import path

# importing views from appblog.
from . import views

# importing all functions from views

urlpatterns = [
    path('', views.home, name = 'home' ),
    path('about', views.about, name = 'about'),
    path('dashboard', views.dashboard, name = 'dashboard'),
    path('signup', views.user_signup, name = 'signup'),
    path('login', views.user_login, name = 'login'),
    path('logout', views.user_logout, name = 'logout'),
    path('addpost', views.add_post, name = 'addpost'),

# importing update& delete function with dynamic id included  
    path('updatepost/<int:id>/', views.update_post, name = 'updatepost'),
    path('deletepost/<int:id>/', views.delete_post, name = 'deletepost'),
]

Online_blog/blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appblog.urls')),
]

Online_blog/blog/appblog/models.py
from django.db import models

# Creating Blogpost model with title and desc fields.
class Blogpost(models.Model):
    title = models.CharField(max_length= 150)
    desc = models.TextField()  

Online_blog/blog/appblog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,UsernameField
from django.contrib.auth.models import User
from django.utils.translation import gettext, gettext_lazy as _
from .models import Blogpost


# Creating signupform from using prebuilt 'usercreationform', changing labels in passwords,  

class SignupForm(UserCreationForm):
    password1 = forms.CharField(label= 'Password', widget= forms.PasswordInput(attrs= {'class' : 'form-control'}))
    password2 = forms.CharField(label = 'Confirm Password (again)', widget= forms.PasswordInput(attrs= {'class' : 'form-control'}))
    class Meta:
        # using required field from prebuilt 'User' model, changing lables and adding styling class.
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        labels = {'first_name': 'First Name', 'last_name': 'Last Name', 'email': 'Email'}
        widgets = {'username': forms.TextInput(attrs = {'class' : 'form-control'}),
        'first_name': forms.TextInput(attrs = {'class' : 'form-control'}), 
        'last_name': forms.TextInput(attrs = {'class' : 'form-control'}),
        'email': forms.EmailInput(attrs = {'class' : 'form-control'})}


# creating loginform from using prebuilt 'authenticationform' , changing styling class in username and label in password. 
class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control'}))
    password = forms.CharField(label =_("Password"),strip = False, widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'class': 'form-control'}))

# creating modelform with model 'Blogpost', changing labels and adding styling class
class Postform(forms.ModelForm):
    class Meta:
        model = Blogpost
        fields = ['title', 'desc']
        labels = {'title': 'Title', 'desc':'Description'}
        widgets = {'title': forms.TextInput(attrs = {'class' : 'form-control'}),
        'desc': forms.Textarea(attrs = {'class' : 'form-control'}), }

Online_blog/blog/appblog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import SignupForm , LoginForm, Postform
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .models import Blogpost
from django.contrib.auth.models import Group


# home page 
def home(request):
    posts = Blogpost.objects.all() #Getting every fields from 'Blogpost' model.
    return render(request, 'appblog/home.html', {'Posts': posts})

# about page 
def about(request):
    return render(request, 'appblog/about.html')


# signup page 
def user_signup(request):
    if request.method == 'POST': #checking for POST data
        form = SignupForm(request.POST) #storing 'Signupform' data in variable.
        if form.is_valid(): #checking the valiidty of form
            user = form.save() #saving user details in variable
            group = Group.objects.get(name = 'Author') #getting author group data from admin panel
            user.groups.add(group) #adding new user to author group
            messages.success(request, 'Congratulations! You have become an Author.')
            return HttpResponseRedirect('/login')
    else: #checking if request is post
        form = SignupForm() #returning blank form
    return render (request, 'appblog/signup.html', {'form': form})

# dashboard page 
def dashboard(request):
    if request.user.is_authenticated: #checking if user is loggedin or not?
        posts = Blogpost.objects.all() #getting data of every blogpost
        user = request.user #storing users detail in variable
        full_name = user.get_full_name () #storing name of user in variable
        gps = user.groups.all() #storing users group name 
        return render(request, 'appblog/dashboard.html', {'Posts': posts, 'fname': full_name, 'groups':gps})
    else: #if user is not authenticated then redirecting to login page.
        return HttpResponseRedirect('/login')

# login page 
def user_login(request):
    if not request.user.is_authenticated: #checking if user is loggedin or not?
        if request.method =='POST': #checking for POST data
            form = LoginForm(request= request, data = request.POST)#storing 'Loginform' data in variable.
            if form.is_valid(): #checking the valiidty of form
                uname = form.cleaned_data['username'] #stroing clean data for name
                upass = form.cleaned_data['password'] #storing clean data for password 
                user = authenticate(username = uname, password = upass) #checking if proper credentials are there
                if user is not None: #if user's credentials are valid
                    login(request, user) #logging in with credentials
                    messages.success(request, 'Logged in successfully!') #msg after successful login
                    return HttpResponseRedirect('/dashboard') 
        else: #for GET data
            form = LoginForm() #blank form returning
        return render(request, 'appblog/login.html', {'form': form})
    else:
        return HttpResponseRedirect('/dashboard')


# logout page
def user_logout(request):
    logout(request) #performing logout with inbuilt 'logout' function
    return HttpResponseRedirect('/')

#adding post
def add_post(request):
    if request.user.is_authenticated: #checking if user is loggedin or not?
        if request.method =='POST': #checking for POST data
            form = Postform(request.POST)#storing 'Postform' data in variable.
            if form.is_valid(): #checking valididty of form
                title = form.cleaned_data['title'] #storing cleaned data of title
                desc = form.cleaned_data['desc'] #storing cleaned data of description
                pst = Blogpost(title = title, desc = desc ) #storing data of model 'Blogpost'
                pst.save() #saving data of variable 
                messages.success(request, 'Post added successfully!') 
                return HttpResponseRedirect('/dashboard')
        else: #checking for get data
            form = Postform() #returning blank form
        return render(request, 'appblog/addpost.html', {'form': form})
    else:
        return HttpResponseRedirect('/login')

#updating post
def update_post(request,id):
    if request.user.is_authenticated: #checking if user is loggedin or not?
        if request.method =='POST': #checking for POST data
            pi = Blogpost.objects.get(pk = id) #getting data of particular id 
            form = Postform(request.POST, instance = pi) #updating data for particular id
            if form.is_valid(): #checking validity of form
                form.save() #saving data 
                messages.success(request, 'Post updated successfully!')
                return HttpResponseRedirect('/dashboard')
        else: #checking for get data
            pi = Blogpost.objects.get(pk = id) #getting data of particular id
            form = Postform(instance = pi) #returning data back for particular id
        return render(request, 'appblog/updatepost.html', {'form': form})
    else:
        return HttpResponseRedirect('/login')


#deleting post
def delete_post(request,id):
    if request.user.is_authenticated: #checking if user is loggedin or not?
        if request.method == 'POST': #checking for POST data
            pi = Blogpost.objects.get(pk = id) #getting data of particular id
            pi.delete() #deleteing data of particular id
        return HttpResponseRedirect('/dashboard')
    else:
        return HttpResponseRedirect('/login')

Online_blog/blog/appblog/templates/appblog/about.html
{% extends 'appblog/base.html' %} 
{% comment %} using pre-built base.html {% endcomment %}

{% load static %}
{% block content %}

<div class="col-sm-10">
<h3 class = "text-white my-5"> About page </h3>

{% comment %} adding random text {% endcomment %}

<p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, iusto accusamus. Odit dolore, blanditiis fuga aspernatur voluptas beatae iusto asperiores, distinctio ab totam nemo, temporibus repellendus atque! Qui pariatur odit libero officiis cumque error fugiat illo, et totam autem impedit, ratione in, reprehenderit sint aperiam doloremque sit possimus magnam. Nulla.</p>
<p> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit distinctio minima earum ipsa rem perspiciatis temporibus deleniti delectus placeat voluptates minus eveniet, obcaecati, libero corporis nemo est veritatis vero quod, molestiae aliquid! Assumenda voluptas est tenetur. Perferendis, totam voluptatem. Ad, impedit deleniti nemo eligendi voluptatum cupiditate error nulla maxime.
</p>
</div>
{% endblock content %}

Online_blog/blog/appblog/templates/appblog/addpost.html
{% extends 'appblog/base.html'%}
{% comment %} using pre-built base.html {% endcomment %}

{% load static %}

{% comment %} displaying messages inside for loop {% endcomment %}
{% block msg %}
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class = "alert alert-{{message.tags}}
alert-dismissible fade show" {% endif %}>
<strong>{{message}}</strong>
</div>
{% endfor %}
{% endif %}
{% endblock msg %}


{% block content %}
<div class = "col-sm-10" </div>
<h3 class = "text-white my-5" > Dashboard/Update post</h3>
<form action="" method="post" novalidate>
{% csrf_token %}

{% comment %} loaded data {% endcomment %}
{{form.as_p}}

{% comment %} add button {% endcomment %}
<input type="submit" value="Add" class = "btn btn-success">

{% comment %} cancel button {% endcomment %}
<a href="{% url 'dashboard' %}" class = "btn btn-danger">Cancel</a>

</form>
</div>
{% endblock content %}

Online_blog/blog/appblog/templates/appblog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% comment %} adding css from  bootstrap {% endcomment %}
    <link rel="stylesheet" href="{% static 'appblog/css/bootstrap.css' %}"> 
    
    {% comment %} adding css from external stylesheet {% endcomment %}
    <link rel="stylesheet" href="{% static 'appblog/css/style.css' %}">
    <title>Document</title>
</head>
<body>
    {% comment %} including navbar {% endcomment %}
    <div class = "container-fluid bg-dark">
    {% include 'appblog/navbar.html' %} 
    </div>

    {% comment %} for msg display {% endcomment %}
    <div class = "container">
        <div class = "row">
            <div class = "col-sm-12" >
                 {% block msg %}
                 {% endblock msg %}
            </div>
       </div>

{% comment %} for side display {% endcomment %}
    <div class="row">
        {% block side %}
        {% endblock side %}

{% comment %} for content display {% endcomment %}
        {% block content %}
        {% endblock content %}
       </div> 
    </div>
    
{% comment %} adding js from source {% endcomment %}
<script> src = {%static 'appblog/js/bootstrap.js'%} </script>  

</body>
</html>

Online_blog/blog/appblog/templates/appblog/dashboard.html
{% extends 'appblog/base.html' %}
{% comment %} using pre-built base.html {% endcomment %}

{% load static %}

{% comment %} displaying messages inside for loop {% endcomment %}
{% block msg %}
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class = "alert alert-{{message.tags}}
alert-dismissible fade show" {% endif %}>
<strong>{{message}}</strong>
</div>
{% endfor %}
{% endif %}
{% endblock msg %}


{% comment %} displaying loggedin authors profile in dashboard {% endcomment %}
{% block side %}
<div class="col-sm-2 text-white my-5 text-center">
    <h4 class = "my-5"> Profile </h4>
    <h5> {{fname}} </h5>
    {% for group in groups %}
    <p> {{group.name}} </p>
    {% endfor %}
</div>
{% endblock side %}


{% comment %} showing blogpost with every element {% endcomment %}
{% block content %}
<div class="col-sm-10">
<h3 class = "text-white mt-5"> Dashboard page </h3>
<a href="{% url 'addpost'%}" class = "btn btn-success"> Add Post </a>
<h4 class = "text-center alert alert-info mt-3"> Show post information </h4>
{% if Posts %}
<table class = "table table-hover bg-white"
<thead>
    {% comment %} heading data {% endcomment %}
    <tr class="text-center">
        <th scope ="col" style ="width:2%"> ID </th>
        <th scope ="col" style ="width:28%"> Title </th>
        <th scope ="col" style ="width:55%"> Description </th>
        <th scope ="col" style ="width:15%"> Action </th>
    </tr>
</thead>
<tbody>
    {% for post in Posts %}
<tr>
    {% comment %} data inside table {% endcomment %}
    <th scope = "row"> {{post.id}}</th>
    <td>{{post.title}}</td>
    <td>{{post.desc}}</td>

    {% comment %} Edit button for both authors and admin  {% endcomment %}
    <td class = "text-center">
        <a href = "{% url 'updatepost' post.id %}" class ="btn btn-warning btn-sm">Edit</a>

        {% comment %} delete button for admins only {% endcomment %}
        {% if perms.appblog.delete_blogpost %}
        <form action="{% url 'deletepost' post.id %}" method="post" class= "d-inline">
            {% csrf_token %}
            <input type="submit" class = "btn btn-danger btn-sm"
            value = "Delete">
        </form>
        {% endif %}
    </td>
</tr>
{% endfor %}
</tbody>
</table>



{% else %}
<h4 class = "text-center alert alert-warning"> No posts found </h4>
{% endif %}
</div>
{% endblock content %}

Online_blog/blog/appblog/templates/appblog/home.html
{% extends 'appblog/base.html' %}
{% comment %} using pre-built base.html {% endcomment %}

{% load static %}
{% block content %}

<div class="col-sm-10">
<h1 class = "my-5"> Welcome to all blogs</h1>

{% comment %} using for loop to display blog content insed jumbotron {% endcomment %}
{% for post in Posts %}
<div class ="jumbotron jumbotron-fluid jumbo-color " >
    <div class="container">
        <h1 class = " font-weight-bold" > {{post.title}} </h1>
        <p class = "font-weight-light">{{post.desc}}</p>
    </div>
</div>
{% endfor %}
<br> <br>
<h5 style="color: offwhite" > <strong> Post your blogs here. </strong> </h5>

{% comment %} redirecting user towards login or signup {% endcomment %}
<a href="{% url 'login'%}" class = "btn btn-success"> I am already a member </a> <br>
<a href="{% url 'signup'%}" class = " my-3 btn btn-warning"> I want to register </a> 
</div>
{% endblock content %}

Online_blog/blog/appblog/templates/appblog/login.html
{% extends 'appblog/base.html' %}
{% comment %} using pre-built base.html {% endcomment %}

{% load static %}

{% block msg %}
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class = "alert alert-{{message.tags}}
alert-dismissible fade show" {% endif %}>
<strong>{{message}}</strong>
</div>
{% endfor %}
{% endif %}
{% endblock msg %}


{% block content %}

<class="col-sm-10">
<h3 class = "text-white my-5"> Enter your credentials </h3>

{% comment %} using post form for getting username and password with for loop  {% endcomment %}
<form action="" method="post" novalidate>
{% csrf_token %}
{% for fm in form %}
<div
    class = "form-group">
    {{fm.label_tag}} {{fm}} <small class = "text-warning"> {{fm.errors|striptags}} </small> <br>
</div>
{% endfor %}

{% comment %} login button {% endcomment %}
<input type="submit" class = "my-1 btn btn-primary" value = "Login">

{% comment %} forloop for non field errors if any  {% endcomment %}
{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class= "alert alert-danger my-3">{{error}}</p>
{% endfor %}
{% endif %}
</form>

{% endblock content %}

Online_blog/blog/appblog/templates/appblog/navbar.html
{% comment %} navbar classes {% endcomment %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">BLOG</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">

          {% comment %} navbar buttons {% endcomment %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>

          {% comment %}buttons for logged in user  {% endcomment %}
          {% if request.user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>

          {% comment %} buttons for non logged in user {% endcomment %}
          {% else %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'signup' %}">Signup</a>
            
          {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </nav>

Online_blog/blog/appblog/templates/appblog/signup.html
{% extends 'appblog/base.html' %}
{% comment %} using pre-built base.html {% endcomment %}

{% load static %}
{% block content %}

<div class="col-sm-10">
<h3 class = "text-white my-5"> Fill up your details</h3>

{% comment %} display messages inside forloop if any {% endcomment %}
{% if messages %}
{% for message in messages %}
<p {% if message.tags %} class = "alert alert-{{message.tags}} mb-5"
{% endif %} > {{message}} </p>
{% endfor %}
{% endif %}

{% comment %} Postform data using forloop   {% endcomment %}
<form action="" method ="post" novalidate>
    {% csrf_token %}
{% for fm in form %}
<div class="form-group">
</div>
{{fm.label_tag}} {{fm}} <small class = "text-warning"> {{fm.errors|striptags}} </small> <br>
{% endfor %}

{% comment %} submit button {% endcomment %}
<input type = "submit" value = "Submit" class = "my-1 btn btn-primary">

{% comment %} displaying non-field errors in forloop {% endcomment %}
{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class= "alert- alert-danger my-3">{{error}}</p>
{% endfor %}
{% endif %}
</form>
</div>
{% endblock content %}

Online_blog/blog/appblog/templates/appblog/updatepost.html
{% extends 'appblog/base.html'%}
{% comment %} using pre-built base.html {% endcomment %}

{% block msg %}
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class = "alert alert-{{message.tags}}
alert-dismissible fade show" {% endif %}>
<strong>{{message}}</strong>
</div>
{% endfor %}
{% endif %}
{% endblock msg %}



{% load static %}
{% block content %}
<div class = "col-sm-10" </div>
<h3 class = "text-white my-5" > Dashboard/Update post</h3>
<form action="" method="post" novalidate>
{% csrf_token %}

{% comment %} loaded data {% endcomment %}
{{form.as_p}}

{% comment %} update button {% endcomment %}
<input type="submit" value="Update" class = "btn btn-success">

{% comment %} cancel button {% endcomment %}
<a href="{% url 'dashboard' %}" class = "btn btn-danger">Cancel</a>

</form>
</div>
{% endblock content %}